### ISSUE TITLE
Crashes on start up.

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Grimoire-Mixins-1.12.2#1]
```
[05:29:34] [Server thread/WARN]: [Grimoire] Trying to apply class transformers.
[05:29:34] [Server thread/WARN]:     - If you got any errors contact the developer immediately.
[05:29:34] [Server thread/WARN]:  
[05:29:34] [Server thread/WARN]: Loaded files (0):
[05:29:34] [Server thread/WARN]:  
[05:29:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: Class net/minecraftforge/fml/common/Loader illegally accessing "package private" member of class org/spongepowered/asm/mixin/transformer/MixinTransformer
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1137) ~[Loader.class:git-CatServer-1.12.2-e796dfc]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594) ~[Loader.class:git-CatServer-1.12.2-e796dfc]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:git-CatServer-1.12.2-e796dfc]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335) ~[FMLCommonHandler.class:git-CatServer-1.12.2-e796dfc]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
```

Crash report:
[crash-2020-08-20_05.29.34-server.txt](https://github.com/CrucibleMC/Grimoire-Mixins-1.12.2/files/5103015/crash-2020-08-20_05.29.34-server.txt)

**Comment by EverNife** [comment]
Try with this Grimoire version:

https://github.com/CrucibleMC/Grimoire/releases/download/v1.0.2a/renameThisPart.Grimoire-1.12.2-1.0.3a.jar

**Comment by Zilacon** [comment]
That fixed it, thanks.
