### ISSUE TITLE
Crafting issues

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Grimoire-Mixins-1.12.2#2]
Getting these errors when im using the latest version of Grimoire + worldedit/botania/industrial foregoing

Many players reporting issues crafting things, machines functioning, items vanishing, etc.

```
[20:21:32] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerContainerEvent$Open@eefb7f6:
java.lang.NoSuchMethodError: net/minecraft/inventory/InventoryCrafting.getSizeInventory()I (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/minecraft_server.1.12.2.jar!/afy.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38) called from class io.github.crucible.grimoire.data.forge.BetterCraftCache (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/grimoire/Forge-Mixin-1.0.1a.jar!/io/github/crucible/grimoire/data/forge/BetterCraftCache.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38).
	at io.github.crucible.grimoire.data.forge.BetterCraftCache.hasAnyNBT(BetterCraftCache.java:15) ~[BetterCraftCache.class:?]
	at io.github.crucible.grimoire.data.forge.BetterCraftCache.findMatchingRecipe(BetterCraftCache.java:48) ~[BetterCraftCache.class:?]
	at net.minecraft.item.crafting.CraftingManager.findMatchingRecipe(CraftingManager.java:525) ~[aku.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.slotChangedCraftingGrid(ContainerCraftingStation.java:173) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftMatrixChanged(ContainerCraftingStation.java:164) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftMatrixChanged(ContainerCraftingStation.java:159) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftingStationGuiOpened(ContainerCraftingStation.java:59) ~[ContainerCraftingStation.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_370_ContainerCraftingStation_onCraftingStationGuiOpened_Open.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:125) [FMLNetworkHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2735) [aed.class:?]
	at slimeknights.tconstruct.tools.common.block.BlockToolTable.openGui(BlockToolTable.java:86) [BlockToolTable.class:?]
	at slimeknights.mantle.block.BlockInventory.onBlockActivated(BlockInventory.java:52) [BlockInventory.class:?]
	at slimeknights.tconstruct.tools.common.block.BlockToolTable.onBlockActivated(BlockToolTable.java:108) [BlockToolTable.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:555) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
```

```
[20:21:32] [Server thread/WARN]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_370_ContainerCraftingStation_onCraftingStationGuiOpened_Open (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_370_ContainerCraftingStation_onCraftingStationGuiOpened_Open)
[20:21:32] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net/minecraft/inventory/InventoryCrafting.getSizeInventory()I (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/minecraft_server.1.12.2.jar!/afy.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38) called from class io.github.crucible.grimoire.data.forge.BetterCraftCache (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/grimoire/Forge-Mixin-1.0.1a.jar!/io/github/crucible/grimoire/data/forge/BetterCraftCache.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38).
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_272]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.NoSuchMethodError: net/minecraft/inventory/InventoryCrafting.getSizeInventory()I (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/minecraft_server.1.12.2.jar!/afy.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38) called from class io.github.crucible.grimoire.data.forge.BetterCraftCache (loaded from jar:file:/home/apoc/Servers/1122-Servers/TKX3/grimoire/Forge-Mixin-1.0.1a.jar!/io/github/crucible/grimoire/data/forge/BetterCraftCache.class by net.minecraft.launchwrapper.LaunchClassLoader@9fdd7e38).
	at io.github.crucible.grimoire.data.forge.BetterCraftCache.hasAnyNBT(BetterCraftCache.java:15) ~[BetterCraftCache.class:?]
	at io.github.crucible.grimoire.data.forge.BetterCraftCache.findMatchingRecipe(BetterCraftCache.java:48) ~[BetterCraftCache.class:?]
	at net.minecraft.item.crafting.CraftingManager.findMatchingRecipe(CraftingManager.java:525) ~[aku.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.slotChangedCraftingGrid(ContainerCraftingStation.java:173) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftMatrixChanged(ContainerCraftingStation.java:164) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftMatrixChanged(ContainerCraftingStation.java:159) ~[ContainerCraftingStation.class:?]
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.onCraftingStationGuiOpened(ContainerCraftingStation.java:59) ~[ContainerCraftingStation.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_370_ContainerCraftingStation_onCraftingStationGuiOpened_Open.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:125) ~[FMLNetworkHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2735) ~[aed.class:?]
	at slimeknights.tconstruct.tools.common.block.BlockToolTable.openGui(BlockToolTable.java:86) ~[BlockToolTable.class:?]
	at slimeknights.mantle.block.BlockInventory.onBlockActivated(BlockInventory.java:52) ~[BlockInventory.class:?]
	at slimeknights.tconstruct.tools.common.block.BlockToolTable.onBlockActivated(BlockToolTable.java:108) ~[BlockToolTable.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:555) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_272]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
```

```
[20:21:28] [Server thread/WARN]: Failed to identify sun.reflect.GeneratedConstructorAccessor246 (untransformed name: sun.reflect.GeneratedConstructorAccessor246)
[20:21:28] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_272]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at appeng.core.sync.GuiBridge.ConstructContainer(GuiBridge.java:379) ~[GuiBridge.class:?]
	at appeng.core.sync.GuiBridge.getServerGuiElement(GuiBridge.java:298) ~[GuiBridge.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:256) ~[NetworkRegistry.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:97) ~[FMLNetworkHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2735) ~[aed.class:?]
	at appeng.util.Platform.openGUI(Platform.java:387) ~[Platform.class:?]
	at appeng.parts.reporting.AbstractPartTerminal.onPartActivate(AbstractPartTerminal.java:120) ~[AbstractPartTerminal.class:?]
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:485) ~[AEBasePart.class:?]
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:827) ~[CableBusContainer.class:?]
	at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:407) ~[BlockCableBus.class:?]
	at appeng.block.AEBaseTileBlock.onBlockActivated(AEBaseTileBlock.java:372) ~[AEBaseTileBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:555) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_272]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor246.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
	at appeng.core.sync.GuiBridge.ConstructContainer(GuiBridge.java:375) ~[GuiBridge.class:?]
	at appeng.core.sync.GuiBridge.getServerGuiElement(GuiBridge.java:298) ~[GuiBridge.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:256) ~[NetworkRegistry.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:97) ~[FMLNetworkHandler.class:git-CatServer-1.12.2-9489fbb]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2735) ~[aed.class:?]
	at appeng.util.Platform.openGUI(Platform.java:387) ~[Platform.class:?]
	at appeng.parts.reporting.AbstractPartTerminal.onPartActivate(AbstractPartTerminal.java:120) ~[AbstractPartTerminal.class:?]
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:485) ~[AEBasePart.class:?]
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:827) ~[CableBusContainer.class:?]
	at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:407) ~[BlockCableBus.class:?]
	at appeng.block.AEBaseTileBlock.onBlockActivated(AEBaseTileBlock.java:372) ~[AEBaseTileBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:555) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_272]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_272]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
```

**Comment by EverNife** [comment]
The first and second logs says that the method ftom BetterCraftCache is not there.

Maybe you are not using the Mixin-Forge, or maybe the Mixing-Forge got an error at loading time.

Can you give us the startup log?

The third log i am not sure if it is caused by Grimoire.

**Comment by Zilacon** [comment]
[message (18).txt](https://github.com/CrucibleMC/Grimoire-Mixins-1.12.2/files/5628991/message.18.txt)
Heres the full server log.
Mixin-Forge was in the grimoire folder.

**Comment by EverNife** [comment]
Even though in the readme its says the mixin-forge is only for client-side, i created a crafting cache in him, but by some reason he is not being injected in your server.

I need to test with the same coremods you are using, i am not at home now, i will test it later.

For now, try removing the Mixin-Forge, he is not required for the other ones to work. This way we will be able to know if the entire Grimoire is not working or only the Mixin Forge.

(Easy to test if it is working by using any worldedit command with a modded item id as argument)

**Comment by Zilacon** [comment]
Alright, its getting late for me so i wont be on much longer.
For future reference im using CatServer for the server software: https://github.com/Luohuayu/CatServer

**Comment by Zilacon** [comment]
Yeah removing forge-mixin fixed the issue.

**Comment by EverNife** [comment]
I need to format my PC, i will test it in one day or two and try to find out the issue.
