### ISSUE TITLE
Botania Mana Bottle causes Crash

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Grimoire-Mixins-1.12.2#3]
Drinking a mana bottle causes this crash:
```
java.lang.NoSuchFieldError: net/minecraft/entity/EntityLivingBase.posX
    at vazkii.botania.common.item.ItemBottledMana.effect(ItemBottledMana.java:611)
    at vazkii.botania.common.item.ItemBottledMana.randomEffect(ItemBottledMana.java:197)
    at vazkii.botania.common.item.ItemBottledMana.onItemUseFinish(ItemBottledMana.java:691)
    at net.minecraft.item.ItemStack.onItemUseFinish(ItemStack.java:260)
    at net.minecraft.entity.EntityLivingBase.onItemUseFinish(EntityLivingBase.java:3145)
    at net.minecraft.entity.player.EntityPlayerMP.onItemUseFinish(EntityPlayerMP.java:1378)
    at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:3027)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2423)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:248)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:467)
    at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:532)
    at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:1297)
    at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:364)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:223)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:937)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
    at java.lang.Thread.run(Thread.java:823)
```

Full crash report:
[message (19).txt](https://github.com/CrucibleMC/Grimoire-Mixins-1.12.2/files/5648008/message.19.txt)

**Comment by EverNife** [comment]
I just finished setting up my pc again.

![image](https://user-images.githubusercontent.com/11357801/101372878-1b9fd000-388b-11eb-8e15-ea476f19be8c.png)

It works on my server, seen  your last log from here https://github.com/CrucibleMC/Grimoire-Mixins-1.12.2/issues/2#issuecomment-737177601, it seems the mod  "Performant" is being loaded before the Grimoire.

Maybe forge changed the ordering method. I will try to run with this mod and check if it is incompatible.

![image](https://user-images.githubusercontent.com/11357801/101373213-789b8600-388b-11eb-80d4-44db4c1026d2.png)

**Comment by EverNife** [comment]
Doesn't seems to be it.

Tested here on Magma and with Performant mod, it works fine, even with performant being loaded before...

**Comment by EverNife** [comment]
Ok, this is a bug, but i was not able to reproduce, tried several of your mods, i was not able to find the exact cause.

**Comment by Zilacon** [comment]
This is on the Tekxit 3 LE modpack on Technic if that helps any.
